-- MySQL Script generated by MySQL Workbench
-- Tue Sep 17 11:54:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_spartan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_spartan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_spartan` DEFAULT CHARACTER SET utf8 ;
USE `bd_spartan` ;

-- -----------------------------------------------------
-- Table `bd_spartan`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_spartan`.`Clientes` (
  `DNI` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(50) NULL,
  `Apellidos` VARCHAR(100) NULL,
  `Telefono` VARCHAR(15) NULL,
  `Dirección` VARCHAR(100) NULL,
  `Correo` VARCHAR(100) NULL,
  `Activo`BOOLEAN,
  `Ruta_foto`VARCHAR(100),
  `NumClientes` INT NOT NULL,
  `Observaciones`VARCHAR(500),
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_spartan`.`Mensualidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_spartan`.`Mensualidad` (
  `Clientes_DNI` VARCHAR(10) NOT NULL,
  `Mes_Ano` VARCHAR (10)NOT NULL,
  `Pagado` BOOLEAN,
  `Fecha` DATE,
  `Precio`double,
  INDEX `fk_Pagados_Clientes_idx` (`Clientes_DNI` ASC),
  PRIMARY KEY (`Mes_Ano`, `Clientes_DNI`),
  CONSTRAINT `fk_Pagados_Clientes`
    FOREIGN KEY (`Clientes_DNI`)
    REFERENCES `bd_spartan`.`Clientes` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;