/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.GestionBD;
import Modelo.Cliente;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * 
 */
public class AltaCliente extends javax.swing.JInternalFrame implements Ventana {

    /**
     * Creates new form AltaCliente
     */
    public AltaCliente() {
        initComponents();
        fotoPerfil = "./src/Imagenes/spartan_default_img.png";
        ImageIcon ii = new ImageIcon(fotoPerfil);
        Image image = ii.getImage();
        Image newimg = image.getScaledInstance(80, 95, java.awt.Image.SCALE_SMOOTH);
        ii = new ImageIcon(newimg);
        lblImg.setIcon(ii);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mniSeleccionIMG = new javax.swing.JMenuItem();
        btnAlta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaObs = new javax.swing.JTextArea();
        label1 = new java.awt.Label();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTlf = new javax.swing.JTextField();
        txtDirecion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblImg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTextPane1);

        jLabel1.setText("jLabel1");

        mniSeleccionIMG.setText("Seleccionar Imagen");
        mniSeleccionIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSeleccionIMGActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mniSeleccionIMG);

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta Cliente");

        btnAlta.setText("Alta");
        btnAlta.setActionCommand("btnAlta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        txtaObs.setColumns(20);
        txtaObs.setRows(5);
        jScrollPane1.setViewportView(txtaObs);
        txtaObs.getAccessibleContext().setAccessibleName("txtAreaObservaciones");

        label1.setText("Observaciones");

        lblImg.setBackground(new java.awt.Color(255, 255, 255));
        lblImg.setComponentPopupMenu(jPopupMenu1);
        lblImg.setOpaque(true);

        jLabel3.setText("DNI");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellidos");

        jLabel6.setText("Dirección");

        jLabel7.setText("Telefono");

        jLabel8.setText("Correo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlta)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtTlf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCorreo))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDirecion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtApellidos)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre)))))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDirecion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(lblImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlta)
                .addGap(19, 19, 19))
        );

        txtDNI.getAccessibleContext().setAccessibleName("DNI");
        txtNombre.getAccessibleContext().setAccessibleName("nombre");
        txtApellidos.getAccessibleContext().setAccessibleName("apellidos");
        txtTlf.getAccessibleContext().setAccessibleName("telefono");
        txtDirecion.getAccessibleContext().setAccessibleName("direccion");
        txtCorreo.getAccessibleContext().setAccessibleName("correo");
        lblImg.getAccessibleContext().setAccessibleName("labelImagen");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        if (validarDatos()) {
            Cliente c = new Cliente();
            c.setDni(txtDNI.getText());
            c.setNombre(txtNombre.getText());
            c.setApellidos(txtApellidos.getText());
            c.setDireccion(txtDirecion.getText());
            c.setTelefono(txtTlf.getText());
            c.setCorreo(txtCorreo.getText());
            c.setObservaciones(txtaObs.getText());
            c.setRuta_foto(fotoPerfil);

            String mensaje = "";
            switch (GestionBD.altaCliente(c)) {
                case 1:
                    mensaje = "Usuario " + c.getNombre() + " dado de alta.";
                    ((Main)getParent().getParent().getParent().getParent().getParent()).recargarHijos();
                    break;
                case 0:
                    mensaje = "Ya existe un usuario con DNI igual a " + c.getDni();
                    break;
                case -1:
                    mensaje = "Sea ha producido un error";
                    break;
                case -2:
                    mensaje = "Sea ha producido un error al crear la mensualidad correspondiente al mes actual";
                    break;
            }
            JOptionPane.showMessageDialog(this, mensaje);
        } else {
            JOptionPane.showMessageDialog(this, "Es necesario introducir los datos");
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void mniSeleccionIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSeleccionIMGActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setMultiSelectionEnabled(false);
        String extensions[] = {"jpg", "jpeg", "png"};
        jfc.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    String path = f.getAbsolutePath().toLowerCase();
                    for (int i = 0, n = extensions.length; i < n; i++) {
                        String extension = extensions[i];
                        if ((path.endsWith(extension) && (path.charAt(path.length() - extension.length() - 1)) == '.')) {
                            return true;
                        }
                    }
                }
                return false;
            }

            @Override
            public String getDescription() {
                return "JPG, JPEG, PNG";
            }
        });

        int i = jfc.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            fotoPerfil = "./src/Imagenes/" + jfc.getSelectedFile().getName();
            if (archivoRepetido(jfc.getSelectedFile().getName())) {
                JOptionPane.showMessageDialog(this, "Ya existe una imagen con ese nombre");
                return;
            }
            try (InputStream is = new FileInputStream(jfc.getSelectedFile());
                    OutputStream os = new FileOutputStream(new File(fotoPerfil))) {

                byte[] buffer = new byte[1024];
                int length;
                while ((length = is.read(buffer)) > 0) {
                    os.write(buffer, 0, length);
                }
                ImageIcon ii = new ImageIcon(fotoPerfil);
                Image image = ii.getImage();
                Image newimg = image.getScaledInstance(90, 100, java.awt.Image.SCALE_SMOOTH);
                ii = new ImageIcon(newimg);
                lblImg.setIcon(ii);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error con imagen: " + ex);
            }
        } else {
            ImageIcon ii = new ImageIcon("./src/Imagenes/spartan_default_img.png");
            Image image = ii.getImage();
            Image newimg = image.getScaledInstance(90, 100, java.awt.Image.SCALE_SMOOTH);
            ii = new ImageIcon(newimg);
            lblImg.setIcon(ii);
        }
    }//GEN-LAST:event_mniSeleccionIMGActionPerformed

    private String fotoPerfil;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JMenuItem mniSeleccionIMG;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDirecion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTlf;
    private javax.swing.JTextArea txtaObs;
    // End of variables declaration//GEN-END:variables

    @Override
    public void recargarDatos() {
        //no hago nada bro, como los politicos xd =)
    }

    private boolean validarDatos() {
        if (txtDNI.getText().isEmpty() || txtNombre.getText().isEmpty() || txtTlf.getText().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    private boolean archivoRepetido(String name) {
        File carpeta = new File("./src/Imagenes");
        File[] archivos = carpeta.listFiles();
        for (File img : archivos) {
            if (img.getName().equals(name)) {
                return true;
            }
        }
        return false;
    }
}
